CREATE TABLE PROCEDURE
(
    ID          BIGINT           NOT NULL
        CONSTRAINT PROCEDURE_PKEY
            PRIMARY KEY,
    COST        DOUBLE PRECISION NOT NULL,
    DESCRIPTION VARCHAR(255)     NOT NULL
);

ALTER TABLE PROCEDURE
    OWNER TO viktorlasenko;

