CREATE TABLE ARTIST_INFO
(
    ID           BIGINT NOT NULL
        CONSTRAINT ARTIST_INFO_PKEY
            PRIMARY KEY,
    CABINET      BIGINT NOT NULL
        CONSTRAINT CABINET_UNIQUE
            UNIQUE,
    PROCEDURE_ID BIGINT
        CONSTRAINT PROCEDURE_ID_REFERENCES_PROCEDURE
            REFERENCES PROCEDURE
);

ALTER TABLE ARTIST_INFO
    OWNER TO viktorlasenko;

