CREATE TABLE APP_USER
(
    ID             BIGINT       NOT NULL
        CONSTRAINT APP_USER_PKEY
            PRIMARY KEY,
    APP_USER_ROLE  VARCHAR(255) NOT NULL,
    DATE_OF_BIRTH  TIMESTAMP    NOT NULL,
    EMAIL          VARCHAR(255) NOT NULL
        CONSTRAINT EMAIL_UNIQUE
            UNIQUE,
    GENDER         VARCHAR(255) NOT NULL,
    NAME           VARCHAR(255) NOT NULL,
    PASSWORD       VARCHAR(255) NOT NULL,
    PATRONYMIC     VARCHAR(255) NOT NULL,
    PHONE_NUMBER   VARCHAR(11)  NOT NULL
        CONSTRAINT PHONE_NUMBER_UNIQUE
            UNIQUE,
    SURNAME        VARCHAR(255) NOT NULL,
    ARTIST_INFO_ID BIGINT
        CONSTRAINT ARTIST_INFO_ID_REFERENCES_ARTIST_INFO
            REFERENCES ARTIST_INFO
);

ALTER TABLE APP_USER
    OWNER TO viktorlasenko;

