CREATE TABLE RECORD
(
    ID           BIGINT       NOT NULL
        CONSTRAINT RECORD_PKEY
            PRIMARY KEY,
    DATE_TIME    TIMESTAMP    NOT NULL,
    VERDICT      VARCHAR(255) NOT NULL,
    CLIENT_ID    BIGINT
        CONSTRAINT CLIENT_ID_REFERENCES_APP_USER
            REFERENCES APP_USER,
    PROCEDURE_ID BIGINT
        CONSTRAINT PROCEDURE_ID_REFERENCES_PROCEDURE
            REFERENCES PROCEDURE
);

ALTER TABLE RECORD
    OWNER TO viktorlasenko;

